version: '3.7'
services:
  frontend: 
    container_name: frontend 
    hostname: frontend
    image: mcr.microsoft.com/dotnet/sdk:5.0
#    image: mcr.microsoft.com/dotnet/framework/sdk:4.8.1    
    command: 
      - dotnet
      - run
      - --no-launch-profile
      - --project 
      - /app
    volumes:
      - './app3:/app'
    ports:
      - '8030:80'
    environment:
      - ASPNETCORE_URLS=http://+:80 
      - ASPNETCORE_ENVIRONMENT=Development     
    networks:
      - net_intranet
  backend: 
    container_name: backend 
    hostname: backtend
    image: mcr.microsoft.com/dotnet/sdk:5.0
#    image: mcr.microsoft.com/dotnet/framework/sdk:4.8.1    
    command: 
      - dotnet
      - run
      - --no-launch-profile
      - --project 
      - /app
    volumes:
      - './app2:/app'
    ports:
      - '8020:80'
    environment:
      - ASPNETCORE_URLS=http://+:80 
      - ASPNETCORE_ENVIRONMENT=Development     
    networks:
      - net_intranet
networks:
  net_intranet: 
